wandb_version: 1

_n_gpu:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: gradients/clf\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/clf\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/clf\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/clf\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/clf\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/clf\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.gamma._type
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.gamma.values
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.gamma.bins
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.0._type
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.0.values
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.0.bins
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.1._type
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.1.values
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.1.bins
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.3._type
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.3.values
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.3.bins
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.7._type
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.7.values
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.7.bins
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.6._type
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.6.values
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.6.bins
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.5._type
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.5.values
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.5.bins
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.4._type
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.4.values
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.4.bins
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.2._type
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.2.values
      5: 1
      6:
      - 1
    - 1: gradients/mixer\.scalar_parameters\.2.bins
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    python_version: 3.8.6
    start_time: 1677727099.787523
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 7
      - 13
      - 23
      4: 3.8.6
      5: 0.13.10
      6: 4.17.0
      8:
      - 4
      - 5
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_bucket_cap_mb:
  desc: null
  value: None
ddp_find_unused_parameters:
  desc: null
  value: None
debug:
  desc: null
  value: '[]'
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_train:
  desc: null
  value: false
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 16
eval_steps:
  desc: null
  value: None
evaluation_strategy:
  desc: null
  value: epoch
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: None
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hub_model_id:
  desc: null
  value: None
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
ignore_data_skip:
  desc: null
  value: false
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
learning_rate:
  desc: null
  value: 5.0e-05
length_column_name:
  desc: null
  value: length
load_best_model_at_end:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
log_level:
  desc: null
  value: -1
log_level_replica:
  desc: null
  value: -1
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: /Users/srchoud/dev/work/explinteractions/trained-models/snli/bertsmall-sm/runs/Mar01_22-18-14_msla0665.local
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 500
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: cosine
max_grad_norm:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: None
mp_parameters:
  desc: null
  value: ''
no_cuda:
  desc: null
  value: false
num_train_epochs:
  desc: null
  value: 4
optim:
  desc: null
  value: adamw_hf
output_dir:
  desc: null
  value: /Users/srchoud/dev/work/explinteractions/trained-models/snli/bertsmall-sm
overwrite_output_dir:
  desc: null
  value: false
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 16
per_device_train_batch_size:
  desc: null
  value: 16
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
prediction_loss_only:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
remove_unused_columns:
  desc: null
  value: true
report_to:
  desc: null
  value: '[''wandb'']'
resume_from_checkpoint:
  desc: null
  value: None
run_name:
  desc: null
  value: /Users/srchoud/dev/work/explinteractions/trained-models/snli/bertsmall-sm
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 500
save_strategy:
  desc: null
  value: epoch
save_total_limit:
  desc: null
  value: None
seed:
  desc: null
  value: 42
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: true
tf32:
  desc: null
  value: None
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 16
use_legacy_prediction_loop:
  desc: null
  value: false
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.01
xpu_backend:
  desc: null
  value: None
