datasets:
  snli:
    end: -1
    file_loc: ${EXPL_INTR_HOME}/data/snli_extended.jsonl
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    label_2_id:
      contradiction: 2
      entailment: 0
      neutral: 1
    name: from-annotation
    phase: test
    start: 0
evaluators:
  auc-comp-hf-phrase-top-k:
    handler: bert-large-cased-snli
    name: auc-comp-hf-phrase
    perturber: auc-comp-hf-phrase
    split_explanation_params:
    - ann
    - relation
    - level
    - label_index
    top_k: 1
  auc-suff-hf-phrase-top-k:
    handler: bert-large-cased-snli
    name: auc-suff-hf-phrase
    perturber: auc-suff-hf-phrase
    split_explanation_params:
    - ann
    - relation
    - level
    - label_index
    top_k: 1
experiments:
  louvain_community:
    dataset: snli
    evaluators:
    - auc-suff-hf-phrase-top-k
    - auc-comp-hf-phrase-top-k
    exp_type: single
    explainers:
      base: louvain_community
    name: louvain_community
explainers:
  louvain_community:
    graph_extractor_params:
      name: attention-bipartite-single-layer-single-head
    handler: bert-large-cased-snli
    name: louvain_community
    scorer: base-attn_weight-phrase
handlers:
  bert-large-cased-snli:
    data_loader_params:
      batchsz: 16
      name: bert-large-cased-snli
    head: 7
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    layer: 23
    model_params:
      name: bert-large-cased-snli
    name: hf-head-layer
    tokenizer_params:
      name: bert-large-cased-snli
perturbers:
  auc-comp-hf-phrase:
    handler: bert-large-cased-snli
    name: auc-comp-hf-phrase
  auc-suff-hf-phrase:
    handler: bert-large-cased-snli
    name: auc-suff-hf-phrase
scorers:
  base:
    handler: None
    name: base
  base-attn_weight-phrase:
    handler: bert-large-cased-snli
    name: base-attn_weight-phrase
