[tool.black]
line-length = 128

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::UserWarning",
]

include = '\.pyi?$'

exclude = '''
(
      __pycache__
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
    | \.idea
    | \.wandb
)
'''
