handlers:
  roberta-base-snli:
    name: hf
    data_loader_params:
      name: roberta-base-snli
      batchsz: 16
    tokenizer_params:
      name: roberta-base-snli
    model_params:
      name: roberta-base-snli
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction

datasets:
  snli:
    name: from-annotation
    label: snli-2-agreement
    phase: test
    file_loc:  ${EXPL_INTR_HOME}/explain_interactions/scripts/agreement/data/snli_extended_2anns_agreement.jsonl
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    label_2_id:
      contradiction: 2
      neutral: 1
      entailment: 0
    start: 0
    end: -1

scorers:
  base:
    name: base
    handler: None

perturbers:
  comp-hf-phrase:
    name: comp-hf-phrase
    handler: roberta-base-snli
  suff-hf-phrase:
    name: suff-hf-phrase
    handler: roberta-base-snli

explainers:
  annotation:
    name: annotation
    scorer: base
    handler: roberta-base-snli
    expl_file:  ${EXPL_INTR_HOME}/explain_interactions/scripts/agreement/data/snli_extended_2anns_agreement.jsonl
    labels:
      entailment: 0
      neutral: 1
      contradiction: 2

evaluators:
  auc-comp-hf-phrase-norm:
    name: auc-norm
    label: auc-comp-hf-phrase-norm
    handler: roberta-base-snli
    perturber: comp-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
  auc-suff-hf-phrase-norm:
    name: auc-norm
    label: auc-suff-hf-phrase-norm
    handler: roberta-base-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
  pha-hf-phrase-norm:
    name: pha-hf-phrase-norm
    label: pha-hf-phrase-norm
    handler: roberta-base-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index


experiments:
  annotation-norm:
    name: annotation-norm
    dataset: snli
    exp_type: single
    explainers:
      base: annotation
    evaluators:
      - auc-suff-hf-phrase-norm
      - auc-comp-hf-phrase-norm
      - pha-hf-phrase-norm
