handlers:
  bert-large-cased-snli:
    name: hf-head-layer-head-importance
    data_loader_params:
      name: bert-large-cased-snli
      batchsz: 8
    tokenizer_params:
      name: bert-large-cased-snli
    model_params:
      name: bert-large-cased-snli
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    layer: 23
    head_importance: -1

datasets:
  snli:
    name: from-annotation
    label: snli
    phase: test
    file_loc: ${EXPL_INTR_HOME}/data/snli_extended.jsonl
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    label_2_id:
      contradiction: 2
      entailment: 0
      neutral: 1
    start: 0
    end: -1

scorers:
  base-attn_weight-phrase:
    handler: bert-large-cased-snli
    name: base-attn_weight-phrase

perturbers:
  comp-hf-phrase:
    name: comp-hf-phrase
    handler: bert-large-cased-snli
  suff-hf-phrase:
    name: suff-hf-phrase
    handler: bert-large-cased-snli

explainers:
  louvain_community:
    graph_extractor_params:
      name: attention-bipartite-single-layer-single-head
    handler: bert-large-cased-snli
    name: louvain_community
    scorer: base-attn_weight-phrase

evaluators:
  auc-comp-hf-phrase-top-k:
    name: auc
    label: auc-comp-hf-phrase-top-k
    handler: bert-large-cased-snli
    perturber: comp-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
    top_k: 1
  auc-suff-hf-phrase-top-k:
    name: auc
    label: auc-suff-hf-phrase-top-k
    handler: bert-large-cased-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
    top_k: 1
  pha-hf-phrase-top-k:
    name: pha-hf-phrase
    label: pha-hf-phrase-top-k
    handler: bert-large-cased-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
    top_k: 1

experiments:
  louvain_community:
    dataset: snli
    evaluators:
      - auc-suff-hf-phrase-top-k
      - auc-comp-hf-phrase-top-k
      - pha-hf-phrase-top-k
    exp_type: single
    explainers:
      base: louvain_community
    name: louvain_community