handlers:
  roberta-large-snli:
    name: &attn_head_chooser name: hf-head-importance-scalar-mix
    data_loader_params:
      name: roberta-large-snli
      batchsz: 8
    tokenizer_params:
       name: &model roberta-large-snli
    model_params:
      name: roberta-large-snli-scalar-mix
      base_model_name: roberta-large-snli
      num_attn_heads: 16
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    layer: 23
    head_importance: -1

datasets:
  snli:
    name: from-annotation
    label: snli
    phase: test
    file_loc: ${EXPL_INTR_HOME}/data/snli_extended.jsonl
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    label_2_id:
      contradiction: 2
      entailment: 0
      neutral: 1
    start: 0
    end: -1

scorers:
  base-attn_weight-phrase:
    handler: roberta-large-snli
    name: base-attn_weight-phrase

perturbers:
  comp-hf-phrase:
    name: comp-hf-phrase
    handler: roberta-large-snli
  suff-hf-phrase:
    name: suff-hf-phrase
    handler: roberta-large-snli

explainers:
  louvain_community:
    graph_extractor_params:
      name: attention-bipartite-single-layer-single-head
    handler: roberta-large-snli
    name: louvain_community
    scorer: base-attn_weight-phrase

top_k: &top_k 3
evaluators:
  auc-comp-hf-phrase-norm-top-k:
    name: auc-norm
    label: auc-comp-hf-phrase-norm-top-k
    handler: roberta-large-snli
    perturber: comp-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
    top_k: *top_k
  auc-suff-hf-phrase-norm-top-k:
    name: auc-norm
    label: auc-suff-hf-phrase-norm-top-k
    handler: roberta-large-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
    top_k: *top_k
  pha-hf-phrase-norm-top-k:
    name: pha-hf-phrase-norm
    label: pha-hf-phrase-norm-top-k
    handler: roberta-large-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
    top_k: *top_k

experiments:
  louvain_community-norm:
    dataset: snli
    evaluators:
      - auc-suff-hf-phrase-norm-top-k
      - auc-comp-hf-phrase-norm-top-k
      - pha-hf-phrase-norm-top-k
    exp_type: single
    explainers:
      base: louvain_community
    name: &explainer_name louvain_community-norm
    expl_save_loc: !join ["${EXPL_INTR_HOME}/explanations/", *explainer_name, -, top-k, -, *top_k, /, *attn_head_chooser, /, *model, .jsonl]