handlers:
  roberta-base-snli:
    name: hf
    data_loader_params:
      name: roberta-base-snli
      batchsz: 16
    tokenizer_params:
      name: roberta-base-snli
    model_params:
      name: roberta-base-snli
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction

datasets:
  snli:
    name: from-annotation
    label: snli
    phase: test
    file_loc: ${EXPL_INTR_HOME}/data/snli_extended.jsonl
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    label_2_id:
      contradiction: 2
      entailment: 0
      neutral: 1
    start: 0
    end: -1

scorers:
  base:
    name: base
    handler: None

perturbers:
  comp-hf-phrase:
    name: comp-hf-phrase
    handler: roberta-base-snli
  suff-hf-phrase:
    name: suff-hf-phrase
    handler: roberta-base-snli

explainers:
  random-phrase:
    name: random-phrase
    scorer: base
    handler: roberta-base-snli
    dataset_name: snli

evaluators:
  auc-comp-hf-phrase-norm:
    name: auc-norm
    label: auc-comp-hf-phrase-norm
    handler: roberta-base-snli
    perturber: comp-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index

  auc-suff-hf-phrase-norm:
    name: auc-norm
    label: auc-suff-hf-phrase-norm
    handler: roberta-base-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index

  pha-hf-phrase-norm:
    name: pha-hf-phrase-norm
    label: pha-hf-phrase-norm
    handler: roberta-base-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index

experiments:
  random-phrase-norm:
    name: random-phrase-norm
    dataset: snli
    exp_type: single
    explainers:
      base: random-phrase
    evaluators:
      - auc-suff-hf-phrase-norm
      - auc-comp-hf-phrase-norm
      - pha-hf-phrase-norm
