handlers:
  bert-base-uncased-fever:
    name: hf-head-layer-random-head
    data_loader_params:
      name: bert-base-uncased-fever
      batchsz: 8
    tokenizer_params:
      name: bert-base-uncased-fever
    model_params:
      name: bert-base-uncased-fever
    id_2_label:
      0: nei
      1: refutes
      2: supports
    layer: 11

datasets:
  fever:
    name: from-annotation
    label: fever
    phase: test
    file_loc: ${EXPL_INTR_HOME}/data/fever_extended.jsonl
    id_2_label:
      0: nei
      1: refutes
      2: supports
    label_2_id:
      supports: 2
      nei: 0
      refutes: 1
    start: 0
    end: -1

scorers:
  base-attn_weight-phrase:
    handler: bert-base-uncased-fever
    name: base-attn_weight-phrase

perturbers:
  comp-hf-phrase:
    name: comp-hf-phrase
    handler: bert-base-uncased-fever
  suff-hf-phrase:
    name: suff-hf-phrase
    handler: bert-base-uncased-fever

explainers:
  louvain_community:
    graph_extractor_params:
      name: attention-bipartite-single-layer-single-head
    handler: bert-base-uncased-fever
    name: louvain_community
    scorer: base-attn_weight-phrase

evaluators:
  auc-comp-hf-phrase-norm-top-k:
    name: auc-norm
    label: auc-comp-hf-phrase-norm-top-k
    handler: bert-base-uncased-fever
    perturber: comp-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
    top_k: 1
  auc-suff-hf-phrase-norm-top-k:
    name: auc-norm
    label: auc-suff-hf-phrase-norm-top-k
    handler: bert-base-uncased-fever
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
    top_k: 1
  pha-hf-phrase-norm-top-k:
    name: pha-hf-phrase-norm
    label: pha-hf-phrase-norm-top-k
    handler: bert-base-uncased-fever
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index
    top_k: 1

experiments:
  louvain_community-norm:
    dataset: fever
    evaluators:
      - auc-suff-hf-phrase-norm-top-k
      - auc-comp-hf-phrase-norm-top-k
      - pha-hf-phrase-norm-top-k
    exp_type: single
    explainers:
      base: louvain_community
    name: &explainer_name louvain_community-norm