handlers:
  bert-large-cased-snli:
    name: hf
    data_loader_params:
      name: bert-large-cased-snli
      batchsz: 16
    tokenizer_params:
      name: bert-large-cased-snli
    model_params:
      name: bert-large-cased-snli
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction

datasets:
  snli:
    name: from-annotation
    label: snli
    phase: test
    file_loc: ${EXPL_INTR_HOME}/explain_interactions/scripts/agreement/data/snli_extended_3anns_agreement.jsonl
    id_2_label:
      0: entailment
      1: neutral
      2: contradiction
    label_2_id:
      contradiction: 2
      entailment: 0
      neutral: 1
    start: 0
    end: -1

scorers:
  base:
    name: base
    handler: None

perturbers:
  comp-hf-phrase:
    name: comp-hf-phrase
    handler: bert-large-cased-snli
  suff-hf-phrase:
    name: suff-hf-phrase
    handler: bert-large-cased-snli

explainers:
  annotation:
    name: annotation
    scorer: base
    handler: bert-large-cased-snli
    expl_file: ${EXPL_INTR_HOME}/explain_interactions/scripts/agreement/data/snli_extended_3anns_agreement.jsonl
    labels:
      entailment: 0
      neutral: 1
      contradiction: 2
  part-phrase:
    name: part-phrase
    scorer: base
    handler: bert-large-cased-snli
    part: part2
    dataset_name: snli
    existing_explainer: annotation

evaluators:
  auc-comp-hf-phrase-norm:
    name: auc-norm
    label: auc-comp-hf-phrase-norm
    handler: bert-large-cased-snli
    perturber: comp-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index

  auc-suff-hf-phrase-norm:
    name: auc-norm
    label: auc-suff-hf-phrase-norm
    handler: bert-large-cased-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index

  pha-hf-phrase-norm:
    name: pha-hf-phrase-norm
    label: pha-hf-phrase-norm
    handler: bert-large-cased-snli
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index

experiments:
  annotation:
    name: annotation
    dataset: snli
    exp_type: single
    explainers:
      base: annotation
    evaluators: []
    log: false
  part-phrase-norm:  # you need to run annotation explainers before this to make sure a part of the explanations come from
    # the annotations
    name: part-phrase-norm
    dataset: snli
    exp_type: single
    existing_explainer: annotation
    explainers:
      base: part-phrase
    evaluators:
      - auc-suff-hf-phrase-norm
      - auc-comp-hf-phrase-norm
      - pha-hf-phrase-norm
