seed: 73
model:
  init_params:
    expl_intr_model: roberta-large-fever
    num_attn_heads: 16
hf_tokenizer: roberta-large
hf_dataset:  fever # can be fever or copenlu/fever_gold_evidence
train_params:
  batch_size: 16
  lr: 5.0e-5
  epochs: 4
  output_path: ${EXPL_INTR_HOME}/trained-models/fever/scalar-mix/rl-sm
