handlers:
  roberta-large-fever:
    name: hf
    data_loader_params:
      name: roberta-large-fever
      batchsz: 16
    tokenizer_params:
      name: roberta-large-fever
    model_params:
      name: roberta-large-fever
    id_2_label:
      0: nei
      1: refutes
      2: supports

datasets:
  fever:
    name: from-annotation
    label: fever
    phase: test
    file_loc: ${EXPL_INTR_HOME}/data/fever_extended.jsonl
    id_2_label:
      0: nei
      1: refutes
      2: supports
    label_2_id:
      supports: 2
      refutes: 1
      nei: 0
    start: 0
    end: -1

scorers:
  base:
    name: base
    handler: None

perturbers:
  comp-hf-phrase:
    name: comp-hf-phrase
    handler: roberta-large-fever
  suff-hf-phrase:
    name: suff-hf-phrase
    handler: roberta-large-fever

explainers:
  annotation:
    name: annotation
    scorer: base
    handler: roberta-large-fever
    expl_file: ${EXPL_INTR_HOME}/data/fever_extended.jsonl
    labels:
      nei: 0
      refutes: 1
      supports: 2

evaluators:
  auc-comp-hf-phrase-norm:
    name: auc-norm
    label: auc-comp-hf-phrase-norm
    handler: roberta-large-fever
    perturber: comp-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index

  auc-suff-hf-phrase-norm:
    name: auc-norm
    label: auc-suff-hf-phrase-norm
    handler: roberta-large-fever
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index

  pha-hf-phrase-norm:
    name: pha-hf-phrase-norm
    label: pha-hf-phrase-norm
    handler: roberta-large-fever
    perturber: suff-hf-phrase
    split_explanation_params:
      - ann
      - relation
      - level
      - label_index

experiments:
  annotation-norm:
    name: annotation-norm
    dataset: fever
    exp_type: single
    explainers:
      base: annotation
    evaluators:
      - auc-suff-hf-phrase-norm
      - auc-comp-hf-phrase-norm
      - pha-hf-phrase-norm
